export const teamColors = [
  { name: "FC 우니온 베를린" },
  { name: "FC 쾰른" },
  { name: "FSV 마인츠 05" },
  { name: "19 New Generation" },
  { name: "20 New Generation" },
  { name: "2012 KOREAN HEROES" },
  { name: "21 KFA" },
  { name: "21 NEW GENERATION" },
  { name: "22 KFA" },
  { name: "22 New Generation" },
  { name: "23 Hard Worker" },
  { name: "23 New Generation" },
  { name: "24 Energetic Player" },
  { name: "AS 로마" },
  { name: "AS 모나코" },
  { name: "AS 생테티엔" },
  { name: "Back to Back" },
  { name: "Ballon d'Or" },
  { name: "Best of Europe 21" },
  { name: "Best of World Cup" },
  { name: "Captain" },
  { name: "Century Club" },
  { name: "Champions of Europe" },
  { name: "Competitors Of Continents" },
  { name: "Decade" },
  { name: "European Best Stars" },
  { name: "FC Ambassador" },
  { name: "FC 낭트" },
  { name: "FC 로리앙" },
  { name: "FC 메스" },
  { name: "FC 바르셀로나" },
  { name: "FC 바젤 1893" },
  { name: "FC 샬케 04" },
  { name: "FC 서울" },
  { name: "FC 아우크스부르크" },
  { name: "FC 안양" },
  { name: "FC 코펜하겐" },
  { name: "FC 포르투" },
  { name: "Free Agent" },
  { name: "Golden Rookies" },
  { name: "Greatest Runner-Ups" },
  { name: "Heroes Of the Team" },
  { name: "Home Grown" },
  { name: "ICON" },
  { name: "ICON The Moment" },
  { name: "Journeyman" },
  { name: "KRC 겡크" },
  { name: "LA 갤럭시" },
  { name: "Legend of the Loan" },
  { name: "Legendary Numbers" },
  { name: "LOSC 릴" },
  { name: "Loyal Heroes" },
  { name: "Man City Icon" },
  { name: "Medalist" },
  { name: "Moments of Glory" },
  { name: "Multi-League Champions" },
  { name: "National Hero Debut" },
  { name: "Nostalgia" },
  { name: "Number 7" },
  { name: "OGC 니스" },
  { name: "PSV" },
  { name: "RB 라이프치히" },
  { name: "RC 랑스" },
  { name: "RCD 마요르카" },
  { name: "RCD 에스파뇰" },
  { name: "Returnees" },
  { name: "SC 프라이부르크" },
  { name: "SD 에이바르" },
  { name: "SD 우에스카" },
  { name: "SL 벤피카" },
  { name: "Spotlight" },
  { name: "SSC 나폴리" },
  { name: "Team K League" },
  { name: "Team Korea Icon" },
  { name: "Top Transfer" },
  { name: "Tournament Best" },
  { name: "Tournament Champions" },
  { name: "TSG 호펜하임" },
  { name: "UEFA EURO 2024" },
  { name: "Unexpected Transfer" },
  { name: "Unsung Players" },
  { name: "Veteran" },
  { name: "VfB 슈투트가르트" },
  { name: "VfL 볼프스부르크" },
  { name: "Wonderboys" },
  { name: "World Cup 2022" },
  { name: "갈라타사라이" },
  { name: "강원 FC" },
  { name: "경남 FC" },
  { name: "광저우 R&F FC" },
  { name: "광저우 에버그란데 타오바오" },
  { name: "광주 FC" },
  { name: "그라나다 CF" },
  { name: "김천 상무" },
  { name: "뉴캐슬 유나이티드" },
  { name: "님 올랭피크" },
  { name: "대구 FC" },
  { name: "대전 하나 시티즌" },
  { name: "데포르티보 알라베스" },
  { name: "디나모 자그레브" },
  { name: "디나모 키이우" },
  { name: "디종 FCO" },
  { name: "라티움" },
  { name: "레드불 잘츠부르크" },
  { name: "레반테 UD" },
  { name: "레스터 시티" },
  { name: "레알 마드리드" },
  { name: "레알 바야돌리드" },
  { name: "레알 베티스" },
  { name: "레알 소시에다드" },
  { name: "레인저스" },
  { name: "롬바르디아 FC" },
  { name: "리버풀" },
  { name: "리즈 유나이티드" },
  { name: "맨체스터 시티" },
  { name: "맨체스터 유나이티드" },
  { name: "몽펠리에 HSC" },
  { name: "미들즈브러" },
  { name: "밀라노 FC" },
  { name: "바샥셰히르" },
  { name: "바이에른 뮌헨" },
  { name: "바이엘 04 레버쿠젠" },
  { name: "발렌시아 CF" },
  { name: "번리" },
  { name: "베네벤토" },
  { name: "베르가모 칼초" },
  { name: "베르더 브레멘" },
  { name: "보루시아 도르트문트" },
  { name: "보루시아 묀헨글라트바흐" },
  { name: "볼로냐" },
  { name: "부산 아이파크" },
  { name: "부천 FC 1995" },
  { name: "브라이턴 호브 앨비언" },
  { name: "블랙번 로버스" },
  { name: "비야레알 CF" },
  { name: "사수올로" },
  { name: "사우샘프턴" },
  { name: "산둥 타이산" },
  { name: "삼프도리아" },
  { name: "상하이 선화" },
  { name: "상하이 하이강" },
  { name: "샤흐타르 도네츠크" },
  { name: "서울 이랜드" },
  { name: "성남 FC" },
  { name: "세비야 FC" },
  { name: "셀타 비고" },
  { name: "셀틱" },
  { name: "셰필드 유나이티드" },
  { name: "수원 FC" },
  { name: "수원 삼성 블루윙즈" },
  { name: "스타드 랭스" },
  { name: "스타드 렌" },
  { name: "스타드 브레스트 29" },
  { name: "스토크 시티" },
  { name: "스트라스부르 알자스" },
  { name: "스파르타 프라하" },
  { name: "스페치아" },
  { name: "스포르팅 CP" },
  { name: "아르미니아 빌레펠트" },
  { name: "아스널" },
  { name: "아약스" },
  { name: "아인트라흐트 프랑크푸르트" },
  { name: "아틀레티코 마드리드" },
  { name: "아틀레틱 빌바오" },
  { name: "안산 그리너스 FC" },
  { name: "앙제 SCO" },
  { name: "애스턴 빌라" },
  { name: "에버턴" },
  { name: "엘라스 베로나" },
  { name: "엘체 CF" },
  { name: "오사수나" },
  { name: "올랭피크 리옹" },
  { name: "올랭피크 마르세유" },
  { name: "왓퍼드" },
  { name: "우디네세" },
  { name: "울버햄프턴 원더러스" },
  { name: "울산 현대" },
  { name: "웨스트 브로미치 앨비언" },
  { name: "웨스트 햄 유나이티드" },
  { name: "유벤투스" },
  { name: "인천 유나이티드" },
  { name: "전남 드래곤즈" },
  { name: "전북 현대 모터스" },
  { name: "제노아" },
  { name: "제주 유나이티드" },
  { name: "지롱댕 보르도" },
  { name: "첼시" },
  { name: "충남 아산 축구단" },
  { name: "카디스 CF" },
  { name: "칼리아리" },
  { name: "크리스털 팰리스" },
  { name: "톈진 진먼후" },
  { name: "토리노" },
  { name: "토트넘 홋스퍼" },
  { name: "파르마" },
  { name: "파리 생제르맹" },
  { name: "페예노르트" },
  { name: "포항 스틸러스" },
  { name: "풀럼" },
  { name: "피오렌티나" },
  { name: "함부르크 SV" },
  { name: "헤르타 BSC" },
  { name: "헤타페 CF" },
  { name: "가나" },
  { name: "그리스" },
  { name: "나이지리아" },
  { name: "남아프리카공화국" },
  { name: "네덜란드" },
  { name: "노르웨이" },
  { name: "대한민국" },
  { name: "덴마크" },
  { name: "독일" },
  { name: "멕시코" },
  { name: "모로코" },
  { name: "미국" },
  { name: "벨기에" },
  { name: "북마케도니아" },
  { name: "북아일랜드" },
  { name: "브라질" },
  { name: "사우디아라비아" },
  { name: "세네갈" },
  { name: "세르비아" },
  { name: "스웨덴" },
  { name: "스위스" },
  { name: "스코틀랜드" },
  { name: "스페인" },
  { name: "슬로바키아" },
  { name: "슬로베니아" },
  { name: "아르헨티나" },
  { name: "아이슬란드" },
  { name: "알제리" },
  { name: "에콰도르" },
  { name: "오스트리아" },
  { name: "우루과이" },
  { name: "우크라이나" },
  { name: "웨일스" },
  { name: "이란" },
  { name: "이집트" },
  { name: "이탈리아" },
  { name: "일본" },
  { name: "잉글랜드" },
  { name: "중국" },
  { name: "체코" },
  { name: "칠레" },
  { name: "카메룬" },
  { name: "코스타리카" },
  { name: "코트디부아르" },
  { name: "콜롬비아" },
  { name: "크로아티아" },
  { name: "튀니지" },
  { name: "튀르키예" },
  { name: "파라과이" },
  { name: "페루" },
  { name: "포르투갈" },
  { name: "폴란드" },
  { name: "프랑스" },
  { name: "핀란드" },
  { name: "헝가리" },
  { name: "호주" },
  { name: "19 UEFA Champions League" },
  { name: "20 K LEAGUE BEST" },
  { name: "20 UEFA Champions League" },
  { name: "21 K LEAGUE BEST" },
  { name: "21 UEFA Champions League" },
  { name: "22 K LEAGUE BEST" },
];
