# Generated by Django 5.2.1 on 2025-05-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('nickname', models.CharField(max_length=100)),
                ('club_value', models.BigIntegerField()),
                ('team_color', models.CharField(max_length=100)),
                ('formation', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
