# Generated by Django 5.2.1 on 2025-05-16 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=32)),
                ('position_id', models.PositiveIntegerField()),
                ('spid', models.BigIntegerField()),
                ('season_id', models.PositiveIntegerField()),
                ('grade', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.manager')),
            ],
        ),
    ]
