# Generated by Django 5.2.1 on 2025-05-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='season_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='spid',
        ),
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='player_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='season',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='team_color',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
