# Generated by Django 5.2.1 on 2025-05-17 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_player_match_id_remove_player_position_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('nickname', models.CharField(max_length=64)),
                ('team_color', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=16)),
                ('player_name', models.CharField(max_length=64)),
                ('season', models.CharField(max_length=64)),
                ('grade', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_temp', to='core.manager')),
            ],
        ),
    ]
