# Generated by Django 5.2.1 on 2025-05-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_playertemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='ouid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
