# Generated by Django 5.2.1 on 2025-05-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notice_resource_update_remove_manager_ouid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('nickname', models.CharField(max_length=100)),
                ('club_value', models.BigIntegerField()),
                ('team_color', models.CharField(max_length=100)),
                ('formation', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
