# Generated by Django 5.2.1 on 2025-05-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_visitorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spid', models.CharField(max_length=16)),
                ('season_id', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('review', models.TextField()),
                ('score', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
