# Generated by Django 5.2.1 on 2025-05-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
