# Generated by Django 5.2.1 on 2025-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_review_bad_review_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='bad',
        ),
        migrations.RemoveField(
            model_name='review',
            name='good',
        ),
        migrations.RemoveField(
            model_name='review',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ip',
        ),
        migrations.AddField(
            model_name='review',
            name='player_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='season_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='teamcolor',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='upgrade_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
