# Generated by Django 5.2.1 on 2025-05-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_review_bad_remove_review_good_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='position',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
