# Generated by Django 5.2.1 on 2025-05-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_review_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
