# Generated by Django 5.2.1 on 2025-05-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_review_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='bad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='good',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
