# Generated by Django 5.2.1 on 2025-05-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_review_bad_review_good'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='spid',
            new_name='pid',
        ),
    ]
