# Generated by Django 5.2.1 on 2025-05-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_spid_review_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_reactions',
            field=models.JSONField(default=dict),
        ),
    ]
